########################################################
# Application CONFIGURATIONS
########################################################
app-properties:
  api-accepted-apps: esb
  api-username: admin
  api-password: admin

#sms items
twilio:
  account_id: AC5b274f17de1cfcf105463db66480bb73
  auth_token: d83a82722409c5cde77c37860bb9863b
  trial_number: +19124058761

########################################################
# DATABASE CONFIGURATIONS
########################################################
spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  h2:
    console:
      enabled: 'true'
  r2dbc:
    url: r2dbc:h2:mem:///elevator_db
    username: admin
    password: pass

#database loggers:.
logging:
  level:
    io:
      r2dbc:
        pool: TRACE
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE
